### ISSUE TITLE
Persistent messages

### ISSUE THREAD

**Issue by ToshY** [tamtamchik/simple-flash#13]
**Is your feature request related to a problem? Please describe.**
No, but it would be nice to have persistent messages.

**Describe the solution you'd like**
Flash messages will not disappear automatically, maybe by providing an optional argument like so:

```
// Default flash message
$flash = new Flash();
$flash->message('Tea.');
// or
$flash->message('Tea.', false);

// Persistent message
$flash = new Flash();
$flash->message('Tea.', true);
```

**Describe alternatives you've considered**
Similar libraries which (sadly) also not include persistent flash messages. 

By the way, I'm using Symfony 5.2 with Bootstrap 5 (beta) and this library is really working out for me. Keep up the good work.

**Comment by tamtamchik** [comment]
Hey @ToshY! Thank you for your feedback! 

In general, it's possible right now by defining custom templates for your messages. I added an example https://github.com/tamtamchik/simple-flash/blob/master/issues/13/index.php

Key points:
- Define your custom template: https://github.com/tamtamchik/simple-flash/blob/master/issues/13/index.php#L12-L33
```php
class Bootstrap5DismissibleTemplate extends BaseTemplate implements TemplateInterface
{
    protected $prefix  = ''; // every line prefix
    protected $postfix = '<br>'; // every postfix
    protected $wrapper = '<div class="alert alert-%s alert-dismissible fade show" role="alert">
                            %s
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>'; // wrapper over messages of same type

    public function wrapMessages($messages, $type)
    {
        $type = ($type == 'error') ? 'danger' : $type;

        return sprintf($this->getWrapper(), $type, $messages);
    }
}
```
- Use your template where it's required. I used it to render error messages just as an example: https://github.com/tamtamchik/simple-flash/blob/master/issues/13/index.php#L54-L59
```php
 <?php
if (flash()->hasMessages('error')) {
    echo flash()->setTemplate(new Bootstrap5DismissibleTemplate())->display('error');
}
echo flash()->setTemplate(TemplateFactory::create(Templates::BOOTSTRAP))->display()
?>
```

Does this solve your problem?

**Comment by tamtamchik** [comment]
On the second thought, I think I understand what you mean. Persistent means the message that will stay forever even if the page is refreshed many times? ;)

**Comment by ToshY** [comment]
Hey @tamtamchik, thanks for the clarification! The example you provided was exactly what I was looking for. 

> On the second thought, I think I understand what you mean.
Persistent means the message that will stay forever even if the page is refreshed many times? ;)

While the example you provided already solved it, that actually sounds like an interesting idea too.

Anyway, I'll like to leave this small example here for people who want to use it in Symfony projects using Twig.

`TwigExtension.php`
```php

use Bootstrap5DismissibleTemplate;
use Tamtamchik\SimpleFlash\Exceptions\FlashTemplateNotFoundException;
use Tamtamchik\SimpleFlash\Flash;
use Tamtamchik\SimpleFlash\TemplateFactory;
use Tamtamchik\SimpleFlash\Templates;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * TwigExtension
 */
class TwigExtension extends AbstractExtension
{

    /**
     * @return TwigFunction[]
     */
    public function getFunctions(): array
    {
        return [
            new TwigFunction('alert_dismissable', [$this, 'showDismissableAlertMessage']),
        ];
    }

    /**
     * @param Flash  $flash
     * @param string $dismissable
     *
     * @return string
     * @throws FlashTemplateNotFoundException
     */
    public function showDismissableAlertMessage(Flash $flash, string $dismissable = 'error'): string
    {
        if ($flash->hasMessages($dismissable))
        {
            return $flash->setTemplate(new Bootstrap5DismissibleTemplate())->display($dismissable);
        }
        return $flash->setTemplate(TemplateFactory::create(Templates::BOOTSTRAP))->display();
    }
}

```
`Controller.php`
```php
...
public function index(Request $request): Response
{
    // Instance
    $flash = new Flash();
    $flash->error('Roses are red, violets are blue, flash messages are cool and so are you.');

    return $this->render('base.html.twig', [
        'flash'   => $flash,
    ]);
}
...
```

`base.html.twig`
```twig
...
    {{ alert_dismissable(flash)|raw }}
...

```

**Comment by tamtamchik** [comment]
Cool, thank you for the feedback and example!
