### ISSUE TITLE
Set template every display call

### ISSUE THREAD

**Issue by Albvadi** [tamtamchik/simple-flash#14]
**Describe the bug**
If you use the `display` function on a different page where you created the message, you always have to specify the template or else displays with base template (a.k.a Bootstrap).

**To Reproduce**
1. Create `create_msg.php` with
```php
<?php
    if( !session_id() ) @session_start();
    require_once('../vendor/autoload.php');

    use Tamtamchik\SimpleFlash\TemplateFactory;
    use Tamtamchik\SimpleFlash\Templates;
    
    flash()->setTemplate(TemplateFactory::create(Templates::TAILWIND))
           ->message('This is a info message with TailwindCSS');
    
    header('Location: msg.php');
?>
```

2. Create `msg.php` with:
```php
<?php
    if( !session_id() ) @session_start();
    require_once('../vendor/autoload.php');
?>

<a href="create_msg.php">Create message</a>

<h2>MESSAGES</h2>
<?php
    if (flash()->hasMessages('info'))
    {
        echo flash()->display('info');
    }
?>
```

3. The message is displayed with Bootstrap template

**Expected behavior**
I expect that if I use `display()`, it will be shown with the same template with which I create the message and that I don´t have to specify the template in each `display()` like `echo flash()->setTemplate(TemplateFactory::create(Templates::TAILWIND))->display('info');`

**Comment by tamtamchik** [comment]
I think there is a gap in the documentation that made it possible. 
You do not need to specify a template every time you create a flash message, instead, you need to define it just before you call `display`, so all the messages will be rendered with the selected template.

For your example, you just need to change the place where you call a `setTemplate` function like this.

1. Remove all related to template code from `create_msg.php`:
```php
<?php
if( !session_id() ) @session_start();
require_once('../vendor/autoload.php');

flash()->message('This is a info message!');

header('Location: msg.php');
```
2. Add template just before you are going to render the message in `msg.php`:
```php
<?php
if (!session_id()) @session_start();
require_once('./vendor/autoload.php');

use Tamtamchik\SimpleFlash\TemplateFactory;
use Tamtamchik\SimpleFlash\Templates;
?>

<a href="create_msg.php">Create message</a>

<h2>MESSAGES</h2>

<?php
if (flash()->hasMessages('info')) {
    echo flash()->setTemplate(TemplateFactory::create(Templates::TAILWIND))->display('info');
}
```

Hope this makes sense and solves your initial problem. 
I think my documentation is not clear about the place where to set the template, and I'll try to fix it.

**Comment by Albvadi** [comment]
Thanks for your answer!

I don´t have problems using the library and I actually using setting the template in before display, like you said.
I only open this issue because for me it seems very verbose and a little ugly add use sentences or create objects in html templates, mixing php (more than use a function) and html code.

Thinking about it, I can think of a couple of alternatives:

- create a second parameter in `display` method with the name of the template, like `display('info', 'tailwind')` or `display('info', 'bulma')`. It could be a breaking change if the template is setted before. You should check before set the template in the `display` method.
- a better option imho it´s create specific methods for every template, like `displayAsTailwind('info')`, `displayAsBulma('info')`, etc... and for custom templates, something like `displayAsCustom('info', TemplateInterface $template)`

If you are not interested in this additions, feel free to close this issue.

Anyway, thank you very much for this package because it is very useful for small handcrafted applications without frameworks. :relaxed:

**Comment by tamtamchik** [comment]
@Albvadi agree, I feel like all the stuff with the template factory is overengineered so I definitely want to simplify it, and your ideas a great! I Will think about it and try to add.

**Comment by tamtamchik** [comment]
Added in 3.0.0
