### ISSUE TITLE
Namespace the function.

### ISSUE THREAD

**Issue by boast** [tamtamchik/simple-flash#4]
Title. Writing in the global scope is bad and is hard to fix if an error occurs. Even a big warning on the gh-page is imho not enough.
##

**Comment by tamtamchik** [comment]
@boast I do believe that this lib will be used in small-sized projects, so there will be no collisions.
Also importing a function with `use function` presented only in 5.6+, and I want to keep backward compatibility with 5.4.

**Comment by boast** [comment]
Sounds OK to me, just keep that possibly open. The ifndef at the start is a
good step too.

**Comment by tamtamchik** [comment]
And yes, @boast thanks for response! Appreciate your interest! :)

**Comment by tamtamchik** [comment]
Will be fixed in v 3.0.0
